---
- name: install jenkins on centos
  hosts: all
  become: true
  tasks:
  - name: install java
    ansible.builtin.yum:
      name: java-1.8.0-openjdk-devel
      state: present

  - name: add jenkins repo
    yum_repository:
      name: jenkins
      description: jenkins repo
      baseurl: http://pkg.jenkins-ci.org/redhat-stable
      gpgcheck: yes

  - name: import gpg key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat/jenkins.io.key

  - name: install jenkins
    ansible.builtin.yum:
      name: jenkins
      state: present
